
- name: pull
  docker_image:
    name: bristechsrm/comms

- name: configure
  copy: src=Comms.config dest=/home/{{ user }}/prd.Comms.config

- name: secrets
  copy: src=/home/vagrant/Comms.secrets.config dest=/home/{{ user }}/secrets.Comms.config

- name: start
  docker_container:
    name: comms
    image: bristechsrm/comms
    state: started
    ports:
     - "8080:8080"
    volumes:
     - /home/{{ user }}/prd.Comms.config:/service/Comms.exe.config
     - /home/{{ user }}/secrets.Comms.config:/service/secrets.config
