
- name: start
  command: docker service create \
    --network {{ overlay_network }} \
    --mount type=bind,source=/home/{{ user }}/Comms.exe.config,target=/service/Comms.exe.config \
    --mount type=bind,source=/home/{{ user }}/secrets.Comms.config,target=/service/Comms.config \
    --name comms \
    bristechsrm/comms
