
- name: leave swarm
  shell: docker swarm leave --force || exit 0

- name: start swarm
  command: docker swarm init --advertise-addr {{ ansible_eth0.ipv4.address }}
  register: swarm_init_output

- name: get token
  command: docker swarm join-token -q worker
  register: swarm_join_token

- set_fact:
    swarm_join_token: "{{ swarm_join_token.stdout }}"
    swarm_master_address: "{{ ansible_eth0.ipv4.address }}:2377"
