
- name: start
  command: docker swarm init --advertise-addr eth0

- name: get token
  command: docker swarm join-token -q worker
  register: swarm_join_token

- debug: var=swarm_join_token.stdout
