---
- include: nodes-apt-docker.yml
- include: nodes-srm-docker.yml
- include: nodes-pip-docker-py.yml
- include: srm-auth.yml
- include: srm-comms.yml
- include: srm-sessions.yml
- include: srm-gateway.yml
- include: srm-frontend.yml
