
- hosts: nodes
  become: yes
  become_method: sudo
  gather_facts: no

  roles:
    - srm-config


- hosts: box3
  become: yes
  become_method: sudo
  gather_facts: no

  roles:
   - srm-auth
   - srm-comms
   - srm-sessions
   - srm-gateway
   - srm-frontend
   - srm-publish
