
Vagrant.configure("2") do |config|

  config.vm.define "mgmt" do |mgmt_config|
      mgmt_config.vm.box = "ubuntu/trusty64"
      mgmt_config.vm.hostname = "mgmt"
      mgmt_config.vm.network "private_network", ip: "10.0.15.20"
      mgmt_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
      mgmt_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
  end

  config.vm.define "box1" do |box1_config|
      box1_config.vm.box = "ubuntu/trusty64"
      box1_config.vm.hostname = "box1"
      box1_config.vm.network "private_network", ip: "10.0.15.11"
      box1_config.vm.network "forwarded_port", guest: 8080, host: 8080
      box1_config.vm.network "forwarded_port", guest: 9090, host: 8081
      box1_config.vm.network "forwarded_port", guest: 9003, host: 9003
      box1_config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
  end

  config.vm.define "box2" do |box2_config|
      box2_config.vm.box = "ubuntu/trusty64"
      box2_config.vm.hostname = "box2"
      box2_config.vm.network "private_network", ip: "10.0.15.12"
      box2_config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
  end

  config.vm.define "box3" do |box3_config|
      box3_config.vm.box = "ubuntu/trusty64"
      box3_config.vm.hostname = "box3"
      box3_config.vm.network "private_network", ip: "10.0.15.13"
      box3_config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
  end
end
