
- name: pull
  docker_image:
    name: bristechsrm/auth

- name: configure
  template: src=Auth.config.j2 dest=/home/{{ user }}/Auth.config

- name: secrets
  copy: src=/home/vagrant/Auth.secrets.config dest=/home/{{ user }}/Auth.secrets.config

- name: start
  docker_container:
    name: auth
    image: bristechsrm/auth
    state: started
    ports:
     - "8080:8080"
    volumes:
     - /home/{{ user }}/Auth.config:/service/Auth.exe.config
     - /home/{{ user }}/Auth.secrets.config:/service/secrets.config
