
- name: pull
  docker_image:
    name: bristechsrm/auth

- name: configure
  template: src=Auth.config.j2 dest=/home/{{ user }}/prd.Auth.config

- name: secrets
  copy: src=/home/vagrant/secrets.Auth.config dest=/home/{{ user }}/secrets.Auth.config

- name: start
  docker_container:
    name: auth
    image: bristechsrm/auth
    state: started
    ports:
     - "8080:8080"
    volumes:
     - /home/{{ user }}/prd.Auth.config:/service/Auth.exe.config
     - /home/{{ user }}/secrets.Auth.config:/service/secrets.config
