
- name: stop
  shell: docker service rm auth || exit 0

- name: start
  command: docker service create \
    --network {{ overlay_network }} \
    --publish {{ auth_port }}:8080 \
    --mount type=bind,source=/home/{{ user }}/Auth.exe.config,target=/service/Auth.exe.config \
    --mount type=bind,source=/home/{{ user }}/Auth.exe.secrets,target=/service/Auth.exe.secrets \
    --mount type=bind,source=/home/{{ user }}/AuthCertificate.pfx,target=/AuthCertificate.pfx \
    --name auth \
    bristechsrm/auth
