version: "2"
services:
  frontend:
    image: bristechsrm/frontend
    volumes:
      - $PWD/build/frontend.config.json:/frontend/public/js/config.json
    ports:
      - "8080:8080"
    restart: unless-stopped
  comms:
    image: bristechsrm/comms
    environment:
      - AWS_ACCESS_KEY_ID=FAKEID
      - AWS_SECRET_ACCESS_KEY=fakeSecret
    volumes:
        - $PWD/build/comms.app.config:/service/Comms.exe.config
    ports:
      - "9000:8080"
    restart: unless-stopped
  sessions:
    image: bristechsrm/sessions
    volumes:
        - $PWD/build/sessions.app.config:/service/Sessions.exe.config
    ports:
      - "9001:8080"
    restart: unless-stopped
  api-gateway:
    image: bristechsrm/api-gateway
    volumes:
        - $PWD/build/api-gateway.app.config:/service/ApiGateway.exe.config
    ports:
      - "9002:8080"
    restart: unless-stopped
    depends_on:
      - auth
  auth:
    image: bristechsrm/auth
    environment:
      - AWS_ACCESS_KEY_ID=FAKEID
      - AWS_SECRET_ACCESS_KEY=fakeSecret
    volumes:
        - $PWD/build/auth.app.config:/service/Auth.exe.config
    ports:
      - "9003:9003"
    restart: unless-stopped
  mysql:
    image: bristechsrm/srm-mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=localdev
    ports:
      - "3306:3306"
    restart: unless-stopped
  dynamodb:
    image: bristechsrm/srm-dynamo-db
    ports:
      - "7000:7000"
    restart: unless-stopped
