
- name: pull
  docker_image:
    name: bristechsrm/sessions

- name: configure
  copy: src=dev.Sessions.config dest=/home/vagrant/Sessions.config

- name: start
  docker_container:
    name: sessions
    image: bristechsrm/sessions
    state: started
    ports:
     - "8080:8080"
    volumes:
     - /home/vagrant/Sessions.config:/service/Sessions.exe.config
