
- name: start
  command: docker service create \
    --network {{ overlay_network }} \
    --mount type=bind,source=/home/{{ user }}/Sessions.exe.config,target=/service/Sessions.exe.config \
    --name sessions \
    bristechsrm/sessions
