
- name: pull
  docker_image:
    name: bristechsrm/sessions

- name: configure
  template: src=Sessions.config.j2 dest=/home/{{ user }}/Sessions.config

- name: start
  docker_container:
    name: sessions
    image: bristechsrm/sessions
    state: started
    ports:
     - "8080:8080"
    volumes:
     - /home/{{ user }}/Sessions.config:/service/Sessions.exe.config
