name             'srm-comms'
maintainer       'Bert the Chicken'
maintainer_email 'bert@example.org'
license          'All rights reserved'
description      'Installs/Configures mycomms'
long_description 'See short description'
version          '0.1.15'
