#!/bin/sh

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

buffer=$(cat)

#Extract variables from json
serviceName=$(echo $buffer | jq -r '.source.serviceName')
nodeName=$(echo $buffer | jq -r '.source.nodeName')
swarmMasterIp=$(echo $buffer | jq -r '.source.swarmMasterIp')
repository=$(echo $buffer | jq -r '.source.repository')
overlay=$(echo $buffer | jq -r '.source.overlay')
accessKeyId=$(echo $buffer | jq -r '.source.accesskeyId')
secretAccessKey=$(echo $buffer | jq -r '.source.secretAccessKey')

#Remove surrounding quotes from repository
#repository=$repository | sed -e 's/^"//'  -e 's/"$//'

export DOCKER_HOST="tcp://${swarmMasterIp}:3376"

docker stop ${serviceName}
docker rm ${serviceName}

docker pull ${repository}

if [ -z "$accessKeyId" ] || [ -z "$secretAccessKey" ]; then
    docker run -d -p 8080:8080 --restart=always --name=${serviceName} --net=${overlay} --env=constraint:node==${nodeName} ${repository}
else
    docker run -d -p 8080:8080 --restart=always --name=${serviceName} --net=${overlay} --env=constraint:node==${nodeName} -e AWS_ACCESS_KEY_ID=${accessKeyId} -e AWS_SECRET_ACCESS_KEY=${secretAccessKey} ${repository}
fi

