
user: "ubuntu"
sessionsdb_str: "SERVER=talks.ch20oh3elz3t.eu-west-1.rds.amazonaws.com;Database=sessions;UID=sessions;Password=;"
consul_address: "10.0.1.137:8500"
auth_address: "10.0.1.77:8080"
comms_address: "10.0.1.181:8080"
sessions_address: "10.0.1.44:8080"
frontend_port: 80
auth_url: "http://auth.bris.tech:8080"
gateway_url: "http://api.bris.tech:8080"
frontend_url: "http://srm.bris.tech"
