
#- name: leave
#  command: docker swarm leave --force

- name: join
  command: docker swarm join \
    --token {{ hostvars['box3']['swarm_join_token'] }} \
    {{ hostvars['box3']['swarm_master_address'] }}
