
- name: leave swarm
  shell: docker swarm leave --force || exit 0

- name: join swarm
  command: docker swarm join \
    --token {{ hostvars['box3']['swarm_join_token'] }} \
    {{ hostvars['box3']['swarm_master_address'] }}
