
- name: start
  command: docker service create \
    --network {{ overlay_network }} \
    --publish {{ frontend_port }}:8080 \
    --mount type=bind,source=/home/{{ user }}/frontend.json,target=/frontend/public/js/config.json \
    --name frontend \
    bristechsrm/frontend
