
- name: pull
  docker_image:
    name: bristechsrm/frontend

- name: configure
  template: src=frontend.json.j2 dest=/home/{{ user }}/prd.frontend.json

- name: start
  docker_container:
    name: frontend
    image: bristechsrm/frontend
    state: started
    ports:
     - "{{ frontend_port }}:8080"
    volumes:
     - /home/{{ user }}/prd.frontend.json:/frontend/public/js/config.json
