
- name: pull
  docker_image:
    name: bristechsrm/frontend

- name: configure
  copy: src=dev.frontend.json dest=/home/vagrant/frontend.json

- name: start
  docker_container:
    name: frontend
    image: bristechsrm/frontend
    state: started
    ports:
     - "8080:8080"
    volumes:
     - /home/vagrant/frontend.json:/frontend/public/js/config.json
