
- name: pull
  docker_image:
    name: bristechsrm/api-gateway

- name: configure
  template: src=Gateway.config.j2 dest=/home/vagrant/Gateway.config

- name: start
  docker_container:
    name: gateway
    image: bristechsrm/api-gateway
    state: started
    ports:
     - "8080:8080"
    volumes:
     - /home/vagrant/Gateway.config:/service/ApiGateway.exe.config
