
- name: stop
  shell: docker service rm gateway || exit 0

- name: start
  command: docker service create \
    --network {{ overlay_network }} \
    --publish {{ gateway_port }}:8080 \
    --name gateway \
    bristechsrm/gateway
