
- name: pull
  docker_image:
    name: bristechsrm/gateway

- name: configure
  template: src=Gateway.config.j2 dest=/home/{{ user }}/prd.Gateway.config

- name: start
  docker_container:
    name: gateway
    image: bristechsrm/gateway
    state: started
    ports:
     - "8080:8080"
    volumes:
     - /home/{{ user }}/prd.Gateway.config:/service/Gateway.exe.config
