
- name: auth config
  template: src=Auth.config.j2 dest=/home/{{ user }}/Auth.exe.config

- name: auth secrets
  copy: src=/vagrant/Auth.exe.secrets dest=/home/{{ user }}/Auth.exe.secrets

- name: auth certificate
  copy: src=/vagrant/AuthCertificate.pfx dest=/home/{{ user }}/AuthCertificate.pfx



- name: comms secrets
  copy: src=/vagrant/Comms.exe.secrets dest=/home/{{ user }}/Comms.exe.secrets



- name: publish secrets
  copy: src=/vagrant/Publish.exe.secrets dest=/home/{{ user }}/Publish.exe.secrets



- name: sessions config
  template: src=Sessions.config.j2 dest=/home/{{ user }}/Sessions.exe.config



- name: frontend config
  template: src=frontend.json.j2 dest=/home/{{ user }}/frontend.json
